-- =========================================================
-- FACILITIES: facility scope and booking ownership.
-- =========================================================

create policy facilities_access_read on public.facilities for select using (app.can_access_facility(id));
create policy facilities_manage_write on public.facilities for all using (app.has_organisation_permission(organisation_id, 'facilities.manage')) with check (app.has_organisation_permission(organisation_id, 'facilities.manage'));
create policy facility_venues_access_read on public.facility_venues for select using (app.can_access_facility(facility_id));
create policy facility_venues_manage_write on public.facility_venues for all using (app.has_facility_permission(facility_id, 'facilities.manage')) with check (app.has_facility_permission(facility_id, 'facilities.manage'));
create policy facility_resources_access_read on public.facility_resources for select using (app.can_access_facility(facility_id));
create policy facility_resources_manage_write on public.facility_resources for all using (app.has_facility_permission(facility_id, 'facilities.manage')) with check (app.has_facility_permission(facility_id, 'facilities.manage'));
create policy availability_access_read on public.resource_availability_rules for select using (exists (select 1 from public.facility_resources resource where resource.id = resource_id and app.can_access_facility(resource.facility_id)));
create policy availability_manage_write on public.resource_availability_rules for all using (exists (select 1 from public.facility_resources resource where resource.id = resource_id and app.has_facility_permission(resource.facility_id, 'facilities.manage'))) with check (exists (select 1 from public.facility_resources resource where resource.id = resource_id and app.has_facility_permission(resource.facility_id, 'facilities.manage')));
create policy bookings_customer_or_facility_read on public.bookings for select using (app.owns_record(customer_id) or exists (select 1 from public.facility_resources resource where resource.id = resource_id and app.has_facility_permission(resource.facility_id, 'bookings.read')));
create policy bookings_customer_insert on public.bookings for insert with check (app.owns_record(customer_id) and app.has_organisation_permission(organisation_id, 'bookings.create'));
create policy bookings_facility_manage_update on public.bookings for update using (exists (select 1 from public.facility_resources resource where resource.id = resource_id and app.has_facility_permission(resource.facility_id, 'bookings.manage'))) with check (exists (select 1 from public.facility_resources resource where resource.id = resource_id and app.has_facility_permission(resource.facility_id, 'bookings.manage')));
create policy booking_check_ins_facility_read on public.booking_check_ins for select using (exists (select 1 from public.bookings booking join public.facility_resources resource on resource.id = booking.resource_id where booking.id = booking_id and (app.owns_record(booking.customer_id) or app.has_facility_permission(resource.facility_id, 'bookings.read'))));
create policy booking_check_ins_facility_write on public.booking_check_ins for all using (exists (select 1 from public.bookings booking join public.facility_resources resource on resource.id = booking.resource_id where booking.id = booking_id and app.has_facility_permission(resource.facility_id, 'bookings.manage'))) with check (app.owns_record(checked_in_by) and exists (select 1 from public.bookings booking join public.facility_resources resource on resource.id = booking.resource_id where booking.id = booking_id and app.has_facility_permission(resource.facility_id, 'bookings.manage')));
create policy facility_staff_self_or_manager_read on public.facility_staff_assignments for select using (app.owns_record(user_id) or app.has_facility_permission(facility_id, 'facilities.manage'));
create policy facility_staff_manager_write on public.facility_staff_assignments for all using (app.has_facility_permission(facility_id, 'facilities.manage')) with check (app.has_facility_permission(facility_id, 'facilities.manage'));
