-- =========================================================
-- ACADEMY: organisation permission plus coach, athlete and guardian relationships.
-- =========================================================

create policy academy_programs_relationship_read on public.academy_programs for select using (app.can_access_academy(id));
create policy academy_programs_manage_write on public.academy_programs for all using (app.has_organisation_permission(organisation_id, 'academy.manage')) with check (app.has_organisation_permission(organisation_id, 'academy.manage'));
create policy academy_classes_relationship_read on public.academy_classes for select using (app.can_access_academy_class(id));
create policy academy_classes_manage_write on public.academy_classes for all using (app.has_organisation_permission((select program.organisation_id from public.academy_programs program where program.id = program_id), 'academy.manage')) with check (app.has_organisation_permission((select program.organisation_id from public.academy_programs program where program.id = program_id), 'academy.manage'));
create policy academy_sessions_relationship_read on public.academy_sessions for select using (app.can_access_academy_session(id));
create policy academy_sessions_manage_write on public.academy_sessions for all using (exists (select 1 from public.academy_classes class join public.academy_programs program on program.id = class.program_id where class.id = class_id and app.has_organisation_permission(program.organisation_id, 'academy.manage'))) with check (exists (select 1 from public.academy_classes class join public.academy_programs program on program.id = class.program_id where class.id = class_id and app.has_organisation_permission(program.organisation_id, 'academy.manage')));
create policy academy_coach_assignments_relationship_read on public.academy_coach_assignments for select using (app.owns_record(coach_id) or app.can_access_academy_class(class_id));
create policy academy_coach_assignments_manage_write on public.academy_coach_assignments for all using (exists (select 1 from public.academy_classes class join public.academy_programs program on program.id = class.program_id where class.id = class_id and app.has_organisation_permission(program.organisation_id, 'academy.manage'))) with check (exists (select 1 from public.academy_classes class join public.academy_programs program on program.id = class.program_id where class.id = class_id and app.has_organisation_permission(program.organisation_id, 'academy.manage')));
create policy academy_enrollments_relationship_read on public.academy_enrollments for select using (app.owns_record(athlete_id) or app.owns_record(enrolled_by) or exists (select 1 from public.athlete_profiles athlete where athlete.user_id = athlete_id and app.owns_record(athlete.guardian_user_id)) or app.can_access_academy(program_id));
create policy academy_enrollments_manage_write on public.academy_enrollments for all using (app.has_organisation_permission((select program.organisation_id from public.academy_programs program where program.id = program_id), 'academy.manage')) with check (app.has_organisation_permission((select program.organisation_id from public.academy_programs program where program.id = program_id), 'academy.manage'));
create policy academy_attendance_relationship_read on public.academy_attendance for select using (app.owns_record(athlete_id) or exists (select 1 from public.athlete_profiles athlete where athlete.user_id = athlete_id and app.owns_record(athlete.guardian_user_id)) or app.can_access_academy_session(session_id));
create policy academy_attendance_coach_write on public.academy_attendance for all using (app.can_manage_academy_session(session_id)) with check (app.owns_record(recorded_by) and app.can_manage_academy_session(session_id));
create policy academy_assessments_owner_or_permission_read on public.academy_assessments for select using (app.owns_record(athlete_id) or exists (select 1 from public.athlete_profiles athlete where athlete.user_id = athlete_id and app.owns_record(athlete.guardian_user_id)) or app.has_organisation_permission(organisation_id, 'academy.assessments.read'));
create policy academy_assessments_permission_write on public.academy_assessments for all using (app.has_organisation_permission(organisation_id, 'academy.assessments.write')) with check (app.owns_record(assessor_id) and app.has_organisation_permission(organisation_id, 'academy.assessments.write'));
create policy progression_owner_or_permission_read on public.athlete_progression_records for select using (app.owns_record(athlete_id) or exists (select 1 from public.athlete_profiles athlete where athlete.user_id = athlete_id and app.owns_record(athlete.guardian_user_id)) or app.has_organisation_permission(organisation_id, 'academy.progression.read'));
create policy progression_permission_write on public.athlete_progression_records for all using (app.has_organisation_permission(organisation_id, 'academy.progression.write')) with check (app.has_organisation_permission(organisation_id, 'academy.progression.write'));
