-- =========================================================
-- SPONSORSHIP: data follows the sponsoring or receiving organisation.
-- =========================================================

create policy sponsors_organisation_read on public.sponsors for select using (app.has_organisation_permission(organisation_id, 'sponsorship.read'));
create policy sponsors_organisation_write on public.sponsors for all using (app.has_organisation_permission(organisation_id, 'sponsorship.manage')) with check (app.has_organisation_permission(organisation_id, 'sponsorship.manage'));
create policy campaigns_organisation_read on public.sponsorship_campaigns for select using (app.has_organisation_permission(organisation_id, 'sponsorship.read'));
create policy campaigns_organisation_write on public.sponsorship_campaigns for all using (app.has_organisation_permission(organisation_id, 'sponsorship.manage')) with check (app.has_organisation_permission(organisation_id, 'sponsorship.manage'));
create policy sponsorship_contracts_campaign_read on public.sponsorship_contracts for select using (exists (select 1 from public.sponsorship_campaigns campaign where campaign.id = campaign_id and app.has_organisation_permission(campaign.organisation_id, 'sponsorship.read')));
create policy sponsorship_contracts_campaign_write on public.sponsorship_contracts for all using (exists (select 1 from public.sponsorship_campaigns campaign where campaign.id = campaign_id and app.has_organisation_permission(campaign.organisation_id, 'sponsorship.manage'))) with check (exists (select 1 from public.sponsorship_campaigns campaign where campaign.id = campaign_id and app.has_organisation_permission(campaign.organisation_id, 'sponsorship.manage')));
create policy sponsorship_placements_campaign_read on public.sponsorship_placements for select using (exists (select 1 from public.sponsorship_campaigns campaign where campaign.id = campaign_id and app.has_organisation_permission(campaign.organisation_id, 'sponsorship.read')));
create policy sponsorship_placements_campaign_write on public.sponsorship_placements for all using (exists (select 1 from public.sponsorship_campaigns campaign where campaign.id = campaign_id and app.has_organisation_permission(campaign.organisation_id, 'sponsorship.manage'))) with check (exists (select 1 from public.sponsorship_campaigns campaign where campaign.id = campaign_id and app.has_organisation_permission(campaign.organisation_id, 'sponsorship.manage')));
create policy sponsorship_deliverables_campaign_read on public.sponsorship_deliverables for select using (exists (select 1 from public.sponsorship_campaigns campaign where campaign.id = campaign_id and app.has_organisation_permission(campaign.organisation_id, 'sponsorship.read')));
create policy sponsorship_reports_campaign_read on public.sponsorship_reports for select using (exists (select 1 from public.sponsorship_campaigns campaign where campaign.id = campaign_id and app.has_organisation_permission(campaign.organisation_id, 'sponsorship.read')));
