-- =========================================================
-- COMPETITION: organiser permission, official assignment and participant relationship.
-- =========================================================

grant select on public.competitions, public.competition_categories, public.competition_matches, public.competition_ranking_entries to anon;
create policy competitions_authorised_or_published_read on public.competitions for select using (status in ('published', 'registration_open', 'in_progress', 'completed') or app.can_access_competition(id));
create policy competitions_manage_write on public.competitions for all using (app.has_organisation_permission(organisation_id, 'competition.manage')) with check (app.has_organisation_permission(organisation_id, 'competition.manage'));
create policy competition_categories_authorised_or_public_read on public.competition_categories for select using (exists (select 1 from public.competitions competition where competition.id = competition_id and (competition.status in ('published', 'registration_open', 'in_progress', 'completed') or app.can_access_competition(competition.id))));
create policy competition_categories_manage_write on public.competition_categories for all using (exists (select 1 from public.competitions competition where competition.id = competition_id and app.has_organisation_permission(competition.organisation_id, 'competition.manage'))) with check (exists (select 1 from public.competitions competition where competition.id = competition_id and app.has_organisation_permission(competition.organisation_id, 'competition.manage')));
create policy competition_registrations_self_or_authorised_read on public.competition_registrations for select using (app.owns_record(participant_user_id) or app.owns_record(registered_by) or app.can_access_competition(competition_id));
create policy competition_registrations_self_insert on public.competition_registrations for insert with check (app.owns_record(registered_by) and app.owns_record(participant_user_id) and exists (select 1 from public.competitions competition where competition.id = competition_id and competition.status = 'registration_open'));
create policy competition_registrations_manage_update on public.competition_registrations for update using (app.can_access_competition(competition_id)) with check (app.can_access_competition(competition_id));
create policy competition_draws_authorised_read on public.competition_draws for select using (app.can_access_competition(competition_id));
create policy competition_draws_manage_write on public.competition_draws for all using (exists (select 1 from public.competitions competition where competition.id = competition_id and app.has_organisation_permission(competition.organisation_id, 'competition.manage'))) with check (exists (select 1 from public.competitions competition where competition.id = competition_id and app.has_organisation_permission(competition.organisation_id, 'competition.manage')));
create policy competition_matches_authorised_or_public_read on public.competition_matches for select using (exists (select 1 from public.competitions competition where competition.id = competition_id and (competition.status in ('published', 'registration_open', 'in_progress', 'completed') or app.can_access_competition(competition.id))));
create policy competition_matches_manage_write on public.competition_matches for all using (exists (select 1 from public.competitions competition where competition.id = competition_id and app.has_organisation_permission(competition.organisation_id, 'competition.manage'))) with check (exists (select 1 from public.competitions competition where competition.id = competition_id and app.has_organisation_permission(competition.organisation_id, 'competition.manage')));
create policy competition_officials_self_or_authorised_read on public.competition_match_officials for select using (app.owns_record(official_id) or app.can_access_competition_match(match_id));
create policy competition_officials_manage_write on public.competition_match_officials for all using (exists (select 1 from public.competition_matches match join public.competitions competition on competition.id = match.competition_id where match.id = match_id and app.has_organisation_permission(competition.organisation_id, 'competition.manage'))) with check (exists (select 1 from public.competition_matches match join public.competitions competition on competition.id = match.competition_id where match.id = match_id and app.has_organisation_permission(competition.organisation_id, 'competition.manage')));
create policy competition_rankings_authorised_or_public_read on public.competition_ranking_entries for select using (exists (select 1 from public.competitions competition where competition.id = competition_id and (competition.status in ('published', 'registration_open', 'in_progress', 'completed') or app.can_access_competition(competition.id))));
create policy competition_rankings_manage_write on public.competition_ranking_entries for all using (exists (select 1 from public.competitions competition where competition.id = competition_id and app.has_organisation_permission(competition.organisation_id, 'competition.manage'))) with check (exists (select 1 from public.competitions competition where competition.id = competition_id and app.has_organisation_permission(competition.organisation_id, 'competition.manage')));
