-- =========================================================
-- PERFORMANCE: athlete/guardian visibility plus explicit organisation permission.
-- =========================================================

create policy athlete_metrics_owner_guardian_or_permission_read on public.athlete_metrics for select using (app.owns_record(athlete_id) or exists (select 1 from public.athlete_profiles athlete where athlete.user_id = athlete_id and app.owns_record(athlete.guardian_user_id)) or app.has_organisation_permission(organisation_id, 'performance.read'));
create policy athlete_metrics_permission_write on public.athlete_metrics for all using (app.has_organisation_permission(organisation_id, 'performance.write')) with check (app.has_organisation_permission(organisation_id, 'performance.write'));
create policy training_records_owner_guardian_or_permission_read on public.training_records for select using (app.owns_record(athlete_id) or exists (select 1 from public.athlete_profiles athlete where athlete.user_id = athlete_id and app.owns_record(athlete.guardian_user_id)) or app.has_organisation_permission(organisation_id, 'performance.read'));
create policy training_records_permission_write on public.training_records for all using (app.has_organisation_permission(organisation_id, 'performance.write')) with check (app.has_organisation_permission(organisation_id, 'performance.write'));
create policy performance_tests_owner_guardian_or_permission_read on public.performance_tests for select using (app.owns_record(athlete_id) or exists (select 1 from public.athlete_profiles athlete where athlete.user_id = athlete_id and app.owns_record(athlete.guardian_user_id)) or app.has_organisation_permission(organisation_id, 'performance.read'));
create policy performance_tests_permission_write on public.performance_tests for all using (app.has_organisation_permission(organisation_id, 'performance.write')) with check (app.has_organisation_permission(organisation_id, 'performance.write'));
create policy recovery_records_owner_guardian_or_permission_read on public.recovery_records for select using (app.owns_record(athlete_id) or exists (select 1 from public.athlete_profiles athlete where athlete.user_id = athlete_id and app.owns_record(athlete.guardian_user_id)) or app.has_organisation_permission(organisation_id, 'performance.read'));
create policy recovery_records_permission_write on public.recovery_records for all using (app.has_organisation_permission(organisation_id, 'performance.write')) with check (app.has_organisation_permission(organisation_id, 'performance.write'));
create policy match_analyses_owner_or_permission_read on public.match_analyses for select using (app.owns_record(athlete_id) or app.has_organisation_permission(organisation_id, 'performance.read'));
create policy match_analyses_permission_write on public.match_analyses for all using (app.has_organisation_permission(organisation_id, 'performance.write')) with check (app.has_organisation_permission(organisation_id, 'performance.write'));
create policy performance_videos_owner_or_permission_read on public.performance_videos for select using (app.owns_record(athlete_id) or app.has_organisation_permission(organisation_id, 'performance.read'));
create policy performance_videos_permission_write on public.performance_videos for all using (app.has_organisation_permission(organisation_id, 'performance.write')) with check (app.has_organisation_permission(organisation_id, 'performance.write'));
create policy performance_reports_owner_or_permission_read on public.performance_reports for select using (app.owns_record(athlete_id) or app.has_organisation_permission(organisation_id, 'performance.read'));
create policy performance_reports_permission_write on public.performance_reports for all using (app.has_organisation_permission(organisation_id, 'performance.write')) with check (app.has_organisation_permission(organisation_id, 'performance.write'));
